routeDeclaration = [
  { path: "/admin/system-admin", obj: "/system_admin/systemadminRoutes" },
  { path: "/admin/system-admin-org", obj: "/system_admin/organizationsRoutes" },
  { path: "/admin/system-admin-modules", obj: "/system_admin/modulesRoutes" },
  { path: "/admin/system-admin-sub-modules", obj: "/system_admin/subModulesRoutes" },
  { path: "/admin/organizations", obj: "/system_admin/organizationsRoutes" },
  { path: "/admin/system-admin-org-permission", obj: "/system_admin/organaizationPermissionRoutes" },
  { path: "/admin/system-admin-departments", obj: "/system_admin/orgDepartmentsRoutes" },
  { path: "/admin/system-admin-roles", obj: "/system_admin/orgUserRoleRoutes" },

  { path: "/admin/org-user-auth", obj: "/admin/userAuthRoutes" },
  { path: "/admin/terms-master", obj: "/admin/termsMasterRoutes" },
  { path: "/admin/renewal-status-master", obj: "/admin/renewalStatusRoutes" },
  { path: "/admin/org-user-access-permisiions", obj: "/admin/orgUserAccessPermissionRoutes" },
  { path: "/admin/org-user", obj: "/admin/userRoutes" },
  { path: "/admin/roles", obj: "/admin/orgUserRoleRoutes" },
  { path: "/admin/org-departments", obj: "/admin/orgDepartmentsRoutes" },
  { path: "/admin/submodules", obj: "/admin/orgSubModulesRoutes" },
  { path: "/admin/common", obj: "/admin/commonRoutes" },
  { path: "/admin/products", obj: "/admin/productsRoutes" },
  { path: "/admin/plans", obj: "/admin/plansRoutes" },
  { path: "/admin/payments", obj: "/admin/paymentsRoutes" },
  { path: "/admin/plan-terms", obj: "/admin/plansTermsRoutes" },
  { path: "/admin/blogs", obj: "/admin/blogsRoutes" },
  { path: "/admin/customers", obj: "/admin/customerRoutes" },
  { path: "/admin/customer-card", obj: "/admin/customerCardRoutes" },
  { path: "/admin/commissions", obj: "/admin/commissionRoutes" },
  { path: "/admin/policy", obj: "/admin/policyRoutes" },
  { path: "/admin/claims", obj: "/admin/claimsRoutes" },
  { path: "/admin/whitelist-ips", obj: "/admin/whitelistIPRoutes" },
  { path: "/admin/secure-payments", obj: "/admin/securePaymentsRoutes" },
  { path: "/admin/affiliates", obj: "/admin/affiliatesRoutes" },
  { path: "/admin/careers", obj: "/admin/careersRoutes" },
  { path: "/admin/contacts", obj: "/admin/contactsRoutes" },
  { path: "/admin/contractors", obj: "/admin/contractorsRoutes" },
  { path: "/admin/real-estate-professionals", obj: "/admin/realestateProfessionalsRoutes" },
  { path: "/admin/customer-reviews", obj: "/admin/customerReviewsRoutes" },
  { path: "/admin/refer-friends", obj: "/admin/referFriendsRoutes" },
  { path: "/admin/zip-code", obj: "/admin/zipCodeRoutes" },
  { path: "/admin/website-pages", obj: "/admin/websitePagesRoutes" },
  { path: "/admin/page-seo", obj: "/admin/pageSeoRoutes" }, 
  { path: "/admin/plan-term-discounts", obj: "/admin/planTermDiscountsRoutes" }, 
  { path: "/admin/market-leaders", obj: "/admin/marketLeadersRoutes" }, 
  { path: "/admin/dashboard", obj: "/admin/dashboardRoutes" }, 
  { path: "/admin/policy-note/", obj: "/admin/policyNoteRoutes" }, 
  { path: "/admin/product-problem/", obj: "/admin/productProblemRoutes"}, 
  { path: "/admin/salesman/", obj: "/admin/salesmanRoutes"}, 
  { path: "/admin/service-call/", obj: "/admin/serviceCallRoutes"}, 
  { path: "/admin/brands/", obj: "/admin/productBrandRoutes"}, 
  { path: "/admin/priority/", obj: "/admin/claimPriority"}, 
  { path: "/admin/holding/", obj: "/admin/holdingPeriodRoutes"}, 
  { path: "/admin/property/", obj: "/admin/propertyTypesRoutes"}, 
  { path: "/admin/audit-trail/", obj: "/admin/auditTrailRoutes"}, 
  { path: "/admin/policy-status/", obj: "/admin/policyStatusRoutes"}, 
  { path: "/admin/payment-status/", obj: "/admin/paymentStatusRoutes"}, 
  { path: "/admin/property-size/", obj: "/admin/propertySizeRoutes"}, 
  { path: "/admin/claim-status/", obj: "/admin/claimTicketSatusRoutes"}, 



     /* { path: "/admin/role", obj: "/admin/userRoleRoutes" },
  { path: "/admin/user", obj: "/admin/userRoutes" },
  { path: "/admin/customer", obj: "/admin/customerRoutes" },
  { path: "/admin/addon-categories", obj: "/admin/addonCategoriesRoutes" },
  { path: "/admin/items", obj: "/admin/itemRoutes" },
  { path: "/admin/plan-terms", obj: "/admin/planTermsRoutes" },  
  { path: "/admin/plans", obj: "/admin/planRoutes" }, */

  //================FRONTEND ============================//
 // { path: "/frontend/", obj: "/frontend/frontendRoutes" },
   { path: "/frontend/common/", obj: "/frontend/commonRoutes" },
  { path: "/frontend/customer-funnel/", obj: "/frontend/customerFunnelRoutes" },
  { path: "/frontend/policies/", obj: "/frontend/policyRoutes" },
  { path: "/frontend/plans/", obj: "/frontend/planRoutes" },
  { path: "/frontend/plan-terms", obj: "/frontend/plansTermsRoutes" },
  { path: "/frontend/contractors", obj: "/frontend/contractorsRoutes" },
  { path: "/frontend/careers", obj: "/frontend/careersRoutes" },
  { path: "/frontend/contacts", obj: "/frontend/contactsRoutes" },
  { path: "/frontend/affiliates", obj: "/frontend/affiliatesRoutes" },
  { path: "/frontend/real-estate-professionals", obj: "/frontend/realestateProfessionalsRoutes" },
  { path: "/frontend/customer-portal", obj: "/frontend/customerPortalRoutes" }
];

module.exports = routeDeclaration;
